### ISSUE TITLE
carousels with slides with images can lose ability to dragEnd

### ISSUE THREAD

**Issue by cd88** [xiaody/react-touch-carousel#10]
Carousel loses snapping, never fires dragEnd

Chrome v68 – Mac OS 10.13.6

I copied the boring example into my project and added images to each slide. If the image on a slide can be dragged as a semi-transparent copy, the carousel never fires dragEnd and sits lazily wherever it is dragged, no longer snapping into position.

Solutions I'm thinking about are:
a way to watch for or prevent this behavior
a dragTimeout prop on the carousel that could accepts a couple customizing parameters but generally forces dragEnd to be triggered in prescribed circumstances.

<img width="1120" alt="touch-carousel-bug-1" src="https://user-images.githubusercontent.com/3270144/45315208-9cbf5f80-b4e8-11e8-8283-ac62b3fa4d73.png">
image being dragged rather than carousel

- 

<img width="1031" alt="touch-carousel-bug" src="https://user-images.githubusercontent.com/3270144/45315365-18b9a780-b4e9-11e8-8071-cfe983f41b5d.png">
just sits there acting coy, still updating the current slide even

**Comment by xiaody** [comment]
We never fully support desktop mouse events. The `touchWithMouseHOC` is only coded for demo usages.

You may try setting `draggable="false"` for the images, I'm not sure whether it would help.

If you just want a simple images carousel for desktop without much fancy effects, I suggest you to use some other packages like the ones I mention in README.

**Comment by celloworld** [comment]
`draggable="false"` totally worked! Thanks for the quick reply.

**Comment by celloworld** [comment]
made a ref to TouchCarousel with `ref={instance => {this.touchCarousel = instance}}`
made a function that calls `this.touchCarousel.go(index)`
the method docs say `.go(targetCursor)` so I knew I wasn't there yet
surprisingly, `this.touchCarousel.go(index * -1)` was the solution

**Comment by Moyal17** [comment]
first of all thank you @bennettstuart  your solution helped me for my site :)
but i got another question for @celloworld :) how did you set a draggable property?
have you configured something in the TouchCarousel.js file?

**Comment by celloworld** [comment]
Not quite, `draggable` is a global attribute as of html 5, part of the [Drag & Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

[MDN - draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable)

> **By default, only text selections, images, and links can be dragged**. For all other elements, the event ondragstart must be set for the drag and drop mechanism to work, as shown in this [comprehensive example](https://developer.mozilla.org/en-US/docs/DragDrop/Drag_Operations).

My issue was specifically about an image, so I used
`<img draggable="false" src={process.env.BACKEND_URL + '/' + item.imageUrl} />`

**Comment by Moyal17** [comment]
Ooo wow.... didnt think about that one :) thank you very much @celloworld :)
