### ISSUE TITLE
Example using `next`

### ISSUE THREAD

**Issue by jimbol** [xiaody/react-touch-carousel#12]
Hello! Great library, I love the control it gives you, but I have a question.

I want to add a `next` button to my `ContainerComponent`, but I don't know the best way to access that method.

```
export function Carousel() {
  return h(TouchCarousel, {
    component: ContainerComponent, // <-- I'd like to pass `next` into this component
    cardCount: 3,
    renderCard,
    loop: false,
  });
}
```

How can I achieve this?

**Comment by jimbol** [comment]
Here is how I was able to get it working. Its not ideal, but I hope it helps someone.

```
export class Carousel extends React.Component {
  render() {
    return h(TouchCarousel, {
      component: (props) => h(ContainerComponent, {
        ...props,
        next: () => this.touchCarousel.next(),
      }),
      ref: (instance) => {
        this.touchCarousel = instance;
      },
      cardCount: 3,
      renderCard,
      loop: false,
    });
  }
}
```

**Comment by xavimajoral** [comment]
Based on @jimbol here's how I did it with React hooks.
`
type SliderProps = {
  position: number;
};

const Slider: React.FC<SliderProps> = ({ position }: SliderProps) => {
  const carousel = useRef({
    next: () => null,
    prev: () => null,
  });

  return (
    <>
      <TouchCarousel
        component={CarouselContainer}
        cardSize={cardSize}
        cardCount={data.length}
        cardPadCount={cardPadCount}
        loop={enableLoop}
        renderCard={renderCard}
        onRest={(index: any) => updateZodiacName(index)}
        defaultCursor={position}
        ref={carousel}
      />
      <LeftArrow
        onClick={() => carousel && carousel.current.prev()}
      />
      <RightArrow
        onClick={() => carousel && carousel.current.next()}
      />
    </>
  );
};
`

**Comment by LuisValgoi** [comment]
thanks @xavimajoral !!!
