### ISSUE TITLE
publish version 0.8.4 to npm public registry

### ISSUE THREAD

**Issue by sundy001** [xiaody/react-touch-carousel#15]
I am working a project which is using 0.8.3 version. Currently we received number of errors, which is fixed in this [commit](https://github.com/xiaody/react-touch-carousel/commit/9c8eaf27680f9088f87bf7ccb1ab10b00645d78e).  Due to the [size](https://bundlephobia.com/result?p=react-touch-carousel@0.9.0) of bundle in 0.9 is 3 times bigger than 0.8. We decided to stay in 0.8. Could it possible to publish the 0.8.4 to npm public registry? Thank you.

**Comment by xiaody** [comment]
Published. Don't really remember why this version is left out.
