### ISSUE TITLE
Vertical option for react-touch-carousel

### ISSUE THREAD

**Issue by ruslan-mystore** [xiaody/react-touch-carousel#2]
looking forward for this options

**Comment by xiaody** [comment]
Umm, we do have a `vertical` option.
https://github.com/xiaody/react-touch-carousel#propsvertical-boolean

**Comment by creotip** [comment]
I mean vertical option with multiple items.
I did it with css, but there is empty space when scrolling in loop mode
```
.carousel-container {
  height: 100%;
  max-width: 960px;
  margin: 0 auto;
  overflow: hidden;
  -ms-touch-action: pan-x;
  touch-action: pan-x;
  position: fixed;
  z-index: 999999999999999;
  top: 0;
}
```

**Comment by ruslan-mystore** [comment]
To remove the empty space when scrolling you have to tweak the cardPadCount

```const cardPadCount = 5```
