### ISSUE TITLE
Disable / enable the carousel's movement

### ISSUE THREAD

**Issue by SaadBazaz** [xiaody/react-touch-carousel#55]
Hey there,
Thanks for this amazing repo. Building something super cool with this, but stuck at a place where I want the Carousel to just freeze or "do nothing" upon **any touch event or any autoplay** etc, if a certain value becomes true.

## Possible Solution
Add a boolean prop, e.g. called "play" which disables or enables the carousel's movement. For example:

```

const [carouselShouldPlay, setCarouselShouldPlay] = useState(true);


...

      <TouchCarousel
          component={Container}
          cardSize={cardSize}
          cardCount={handData.length}
          cardPadCount={cardPadCount}
          renderCard={renderCard}
          play={carouselShouldPlay}
      />

...
```

If there's already a way to do this, please help me out.

**Comment by xiaody** [comment]
Maybe you can turn off `autoplay` and add `pointer-events: none` css on your container?

**Comment by SaadBazaz** [comment]
The ```pointer-events: none``` was a good suggestion. Went with that!
