### ISSUE TITLE
Support Horizontal Scroll

### ISSUE THREAD

**Issue by SaadBazaz** [xiaody/react-touch-carousel#56]
Hey there,
Most carousels support horizontal scrolling e.g. if you scroll with two fingers on a trackpad in the horizontal direction. Can there be a prop to support that?

**Comment by xiaody** [comment]
Two fingers scrolling sounds a desktop feature, while this library is focused on mobile. I think it's beyond the scope.

**Comment by SaadBazaz** [comment]
Good call.
