### ISSUE TITLE
How to get center Index (cursor) in the beginning?

### ISSUE THREAD

**Issue by SaadBazaz** [xiaody/react-touch-carousel#57]
Hi,
I use onRest to update the center card index, but the problem is that onRest is not called on the initialization of the carousel (I think it should, or there should be a boolean prop for that).

How can I get the center card index / cursor?

**Comment by xiaody** [comment]
Maybe you are talking about [props.defaultCursor](https://github.com/xiaody/react-touch-carousel#propsdefaultcursor-number)? Which is `0` by default.

**Comment by SaadBazaz** [comment]
Yep! Used that to manage it at the beginning. Thanks!
